onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@signalapp/sqlcipher'
  - electron
  - electron-winstaller
  - esbuild
  - libsession_util_nodejs
  - protobufjs
  - sharp

publicHoistPattern:
  - '@img/*'
