name: 'Make release build'
description: '[macOS only] Build a release for a specific cpu architecture and update the release metadata if needed.'
inputs:
  # See 'arch' in https://www.electron.build/cli.html#targetconfiguration
  architecture:
    description: 'cpu architecture'
    required: true
    default: 'x64'
    options:
      - x64
      - arm64
  should_publish:
    description: 'should publish'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Build but do not publish
      # always run this, except on "push" to "master" or alpha releases
      if: ${{ inputs.should_publish == 'false' }}
      shell: bash
      run: |
        source ./build/setup-mac-certificate.sh
        yarn build-release --config.mac.bundleVersion=${{ github.ref }}

    - name: Upload artefacts
      # always run this, except on "push" to "master" or alpha releases
      if: ${{ inputs.should_publish == 'false' }}
      uses: ./actions/upload_prod_artefacts
      with:
        upload_prefix: mac-${{ inputs.architecture }}

    - name: Build & publish
      # only run this on "push" to "master" or alpha releases
      if: ${{ inputs.should_publish == 'true' }}
      shell: bash
      run: |
        source ./build/setup-mac-certificate.sh
        yarn build-release-publish --config.mac.bundleVersion=${{ github.ref }}

      # Note: We need to backup the latest.yml file because other jobs can overwrite it when they are complete e.g. macOS arm64 and x64
    - name: Backup release metadata
      # only run this on "push" to "master" or alpha releases
      if: ${{ inputs.should_publish == 'true' }}
      shell: bash
      run: |
        echo "Backup release metadata for ${{ inputs.architecture }}"
        mv dist/latest-mac.yml dist/latest-mac-${{ inputs.architecture }}-${{ github.sha }}.yml

    - name: Upload release metadata
      # only run this on "push" to "master" or alpha releases
      if: ${{ inputs.should_publish == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: latest-mac-${{ inputs.architecture }}-${{ github.sha }}.yml
        path: dist/latest-mac-${{ inputs.architecture }}-${{ github.sha }}.yml
