when:
  - path:
      exclude: ['*.md']
    event: "push"

steps:
  python:
    image: docker.io/ubuntu:22.04
    commands:
      - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
      - apt-get update
      - apt-get install software-properties-common -y
      - add-apt-repository ppa:deadsnakes/ppa -y
      - apt-get update
      - apt-get install python3.12 python3-pip -y
      - python3 -m pip install --upgrade pip setuptools
  yarn:
    image: codeberg.org/woodpecker-plugins/node-pm
    settings:
      run: ["install", "build-everything"]
      with: yarn
      frozen_lockfile: true
  publish:
    image: woodpeckerci/plugin-release
    settings:
      files:
        - "release/*.AppImage"
      api_key:
        from_secret: ACCESS_TOKEN
