when:
  - path:
      exclude: ['*.md']
    event: ["push", "tag"]
    branch: ["woodpecker-ci", "dev-gravel"]

steps:
  build:
    image: docker.io/python:3.12-bookworm
    commands:
      - apt-get update
      - python3 -m pip install --upgrade pip setuptools
      - apt-get install git build-essential cmake -y
      - curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell --install-dir "/.fnm"
      - export PATH="/.fnm:$PATH"
      - eval "$(fnm env --shell bash)"
      - fnm install
      - fnm use
      - if ! which yarn; then npm install --global yarn; fi
      - yarn install --frozen-lockfile --network-timeout 600000
      - yarn build-everything
      - yarn build-release --linux appImage
    entrypoint: ["/bin/bash", "-c", "echo $CI_SCRIPT | base64 -d | /bin/bash -e"]

  publish:
    image: woodpeckerci/plugin-release
    settings:
      files:
        - "release/*.AppImage"
      api_key:
        from_secret: ACCESS_TOKEN
    when:
      event: tag
