when:
  - path:
      exclude: ['*.md']
    event: "push"

steps:
  build:
    image: docker.io/python:3.12-bookworm
    commands:
      - apt-get update
      - python3 -m pip install --upgrade pip setuptools
      - apt-get install git build-essential cmake -y
      - curl -o- https://fnm.vercel.app/install | bash
      - fnm install 18.15.0
      - if ! which yarn; do npm install --global yarn; done
      - yarn install --frozen-lockfile --network-timeout 600000
      - yarn build-everything

  publish:
    image: woodpeckerci/plugin-release
    settings:
      files:
        - "release/*.AppImage"
      api_key:
        from_secret: ACCESS_TOKEN
