when:
  - path:
      exclude: ['*.md']
    event: "push"

steps:
  python:
    image: docker.io/python:3.12-bookworm
    commands:
      - python3 -m pip install --upgrade pip setuptools
  yarn:
    image: docker.io/node:18.15.0
    commands:
      - apt-get update
      - apt-get install build-essential cmake
      - yarn install --frozen-lockfile --network-timeout 600000
      - yarn build-everything
  publish:
    image: woodpeckerci/plugin-release
    settings:
      files:
        - "release/*.AppImage"
      api_key:
        from_secret: ACCESS_TOKEN
